version: "2"
services:
  jupyterlab:
    ## 構築済みコンテナを使う場合 (default)
    image: docker.pkg.github.com/tkobaya/csc.t364/csc_t364_jupyterlab:latest
    
    ## 手元でコンテナを構築する場合は以下2行のコメントを外す
#    build:
#      context: .

    user: root
    ports:
      - "8888:8888"
    volumes:
#      - "/Users/yourname/bda-work:/home/jovyan/work" # for Mac
      - "/C/Users/yourname/bda-work:/home/jovyan/work" # for Windows
    environment:
      GRANT_SUDO: "yes"
    command: start.sh jupyter lab

## docker-compouse -d up で起動
## docker-compouse exec jupyterlab bash で jupyterlab コンテナにログイン
